version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-gui-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-arm64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
          name: Build image
          command: |
            docker buildx build -f ./gui/Dockerfile --platform linux/amd64 -t respiraworks/gui:$CIRCLE_SHA1 ./gui

workflows:
  commit:
    jobs:
      - build-gui-image
