version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-gui-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
        name: Install buildx
        command: |
          BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64"

workflows:
  commit:
    jobs:
      - build-gui-image
