version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-gui-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout

workflows:
  commit:
    jobs:
      - build-gui-image
