version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-gui-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: respirworks/gui
          dockerfile: ./gui/Dockerfile

workflows:
  commit:
    jobs:
      - build-gui-image
